/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JazzServer {
  static start(options: { appId: string; backendSecret: string; adminSecret: string; port?: number; dataDir?: string; inMemory?: boolean; jwksUrl?: string; allowLocalFirstAuth?: boolean; upstreamUrl?: string; telemetryCollectorUrl?: string }): Promise<JazzServer>
  get appId(): string
  get url(): string
  get port(): number
  get dataDir(): string
  get backendSecret(): string
  get adminSecret(): string
  stop(): Promise<void>
}

export declare class NapiRuntime {
  /** Create a new NapiRuntime with SQLite-backed persistent storage. */
  constructor(schemaJson: string, appId: string, jazzEnv: string, userBranch: string, dataPath: string, tier?: string | undefined | null, releaseDeclaredIndexes?: boolean | undefined | null)
  /** Create a new NapiRuntime with in-memory storage (no local persistence). */
  static inMemory(schemaJson: string, appId: string, jazzEnv: string, userBranch: string, tier?: string | undefined | null): NapiRuntime
insert(table: string, values: Record<string, unknown>, writeContextJson?: string | undefined | null, objectId?: string | undefined | null): { id: string; values: any[]; batchId: string }
update(objectId: string, values: any, writeContextJson?: string | undefined | null): any
upsert(table: string, objectId: string, values: Record<string, unknown>, writeContextJson?: string | undefined | null): any
delete(objectId: string, writeContextJson?: string | undefined | null): any
restore(table: string, objectId: string, values: Record<string, unknown>, writeContextJson?: string | undefined | null): { id: string; values: any[]; batchId: string }
onMutationError(callback: (event: any) => void): void
rollbackBatch(batchId: string): boolean
beginBatch(batchMode: string): string
commitBatch(batchId: string): void
waitForBatch(batchId: string, tier: string): Promise<void>
query(queryJson: string, sessionJson?: string | undefined | null, tier?: string | undefined | null, optionsJson?: string | undefined | null): Promise<any>
unsubscribe(handle: number): void
/** Phase 1 of 2-phase subscribe: allocate a handle and store query params. */
createSubscription(queryJson: string, sessionJson?: string | undefined | null, tier?: string | undefined | null, optionsJson?: string | undefined | null): number
/** Phase 2 of 2-phase subscribe: compile, register, sync, attach callback, tick. */
executeSubscription(handle: number, onUpdate: (...args: any[]) => any): void
getSchema(): any
getSchemaHash(): string
flush(): void
/** Flush and close the underlying storage, releasing filesystem locks. */
close(): void
/**
 * Connect to a Jazz server over WebSocket.
 *
 * Parses `auth_json` into `AuthConfig`, wires a `TransportManager` into
 * `RuntimeCore` via `install_transport` (which seeds the catalogue state
 * hash on the handle), and spawns the manager loop as a Tokio task.
 */
connect(url: string, authJson: string): void
/** Disconnect from the Jazz server and drop the transport handle. */
disconnect(): void
/** Push updated auth credentials into the live transport. */
updateAuth(authJson: string): void
/**
 * Register a JS callback that fires when the Rust transport receives an
 * auth rejection from the server during the WS handshake.
 *
 * The callback receives a single string argument: the rejection reason.
 */
onAuthFailure(callback: (reason: string) => void): void
}

export declare class TestJwtIssuer {
  static start(): Promise<TestJwtIssuer>
  get jwksUrl(): string
  jwtForUser(userId: string, claims?: Record<string, unknown> | undefined, options?: { expiresInSeconds?: number; issuer?: string } | undefined): string
  stop(): Promise<void>
}

export declare function mintLocalFirstToken(seedB64: string, audience: string, ttlSeconds: number): string

export declare function verifyLocalFirstIdentityProof(token: string | undefined | null, expectedAudience: string): VerifyTokenResult

export interface VerifyTokenResult {
  ok: boolean
  id: string
  error?: string
}
